/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo1;

import java.util.ArrayList;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Vinnys
 */

public class PruebaInterfaz extends javax.swing.JFrame {
private static ArrayList<String> lista= new ArrayList<String>();
    /**
     * Creates new form PruebaInterfaz
     */
    public PruebaInterfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(615, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(365, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        XYSeries oSeries = new XYSeries("Prueba");
        XYSeries oSeries2 = new XYSeries("Prueba");
        XYSeries oSeries3 = new XYSeries("Prueba");
        
        double resultado;
        
        double anterior=0.0;
        double actual=0.0;
        String dato="Inicia";
        
        String inflexion="";
        System.out.println("____Busqueda exhaustiva____");
        lista.add("____Busqueda exhaustiva____");
        beMet();
        
        for (double i = 0.0; i <= 1.0; i+=0.1) {
            resultado=fx(i);
            if(i==0.0){
                actual=resultado;
            }else{
                anterior=actual;
                actual=resultado;
            }
            oSeries.add(i,resultado);
        }
        
        
        
        System.out.println("____Busqueda de la seccion dorada____");
        lista.add("____Busqueda de la seccion dorada____");
        //ArrayList<String> lista= new ArrayList<String>();
        bsdRec(0, 1, 0);
        
        System.out.println("____Busqueda de newton____");
        lista.add("____Busqueda de newton____");
        mnrMet(0, 1, 0.5,0);
        
        
        
        /*for (int i = 0; i < lista.size(); i++) {
            System.out.println("");
        }*/
        XYSeriesCollection oDataSet = new XYSeriesCollection();
        oDataSet.addSeries(oSeries);
        //oDataSet.addSeries(oSeries2);
        //oDataSet.addSeries(oSeries3);

        
        JFreeChart oChart = ChartFactory.createXYLineChart("Ejemplo grafica","X","Y", oDataSet,PlotOrientation.VERTICAL, true, false, false);
        
        ChartPanel oPanel = new ChartPanel(oChart);
        
        pnlMain.setLayout(new java.awt.BorderLayout());
        pnlMain.add(oPanel);
        pnlMain.validate();
        
        
    }                                        
    
    public static void mnrMet(double a,double b,double x,int cont){
        double epsilon=1e-6;
        double fx1;
        double fx2;
        
        double xAnterior=x;
        boolean condicion=true;
        while(condicion!=false){
             fx1=f1x(x);
             fx2=f2x(x);
             xAnterior=x;
             x=xAnterior-(fx1/fx2);
             cont++;
             lista.add("i: "+cont+", X: "+x+", f(x): "+fx(x));
             System.out.println("i: "+cont+", X: "+x+", f(x): "+fx(x));
             if(Math.abs(x-xAnterior)<=epsilon){
                System.out.println("________________________");
                System.out.println("X: "+x+", f(x): "+fx(x));
                //lista.add("________________________");
                //lista.add("X: "+x+", f(x): "+fx(x));
                condicion=false;
                break;
            }
        }
    }
    public static void beMet(){
        double resultado=0.0;
        String dato="Inicia";
        double anterior=0.0;
        double actual=0.0;
        
        for (double i = 0.0; i <= 1.0; i+=0.1) {
            resultado=fx(i);
            if(i==0.0){
                actual=resultado;
            }else{
                if(anterior<actual){
                    if(dato.equals("disminuyo")){
                        lista.add("Punto de inflexion minimo en el punto anterior");
                        System.out.println("Punto de inflexion minimo en el punto anterior");
                    }
                    dato="aumento";  
                }
                if(anterior>actual){
                    if(dato.equals("aumento")){
                        lista.add("Punto de inflexion maximo en el punto anterior");
                        System.out.println("Punto de inflexion maximo en el punto anterior");
                    }
                    dato="disminuyo";
                }
                anterior=actual;
                actual=resultado;
            }
            lista.add("i: "+i+" : "+resultado+" : "+dato);
            System.out.println("i: "+i+" : "+resultado+" : "+dato);
        }
    }
    public static void bsdRec(double a,double b, double iteraciones){
        double tau= 2 -1.618033988;
        double epsilon=1e-6;
        
        double a1=a*(1-tau)+b*tau;
        double a2=a*tau+b*(1-tau);
        
        double fa1=fx(a1);
        double fa2=fx(a2);
        
        if(fa1>fa2){
            a=a1;
        }else{
            b=a2;
        }
        if(Math.abs(fa1-fa2)>epsilon){
            iteraciones++;
            lista.add("i: "+iteraciones+", a1: "+a1+", fa1="+fa1);
            System.out.println("i: "+iteraciones+", a1: "+a1+", fa1="+fa1);
            bsdRec(a,b,iteraciones);
        }else{
                System.out.println(":________________________________________________");
                System.out.println("A1= "+a1+", f(a1)= "+fx(a1));
                System.out.println(":________________________________________________");
        }
    }
    
    public static double fxEjemplo(double x){
        return -2*Math.sin(x)+((x*x)/10);
    }
    
    public static double fx(double x){
        return x*x +Math.sin(x);
    }
    public static double f1x(double x){
        return 2*x+Math.cos(x);
    }
    public static double f2x(double x){
        return 2+Math.sin(x);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaInterfaz().setVisible(true);
                
                
            }
        });
        
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration                   
}
